<a href="https://colab.research.google.com/github/rakenputra/machine-learning/blob/main/UAS/%20Chapter%200/Python_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Raken Putra Athallah
#1103204186

PyTorch adalah framework open-source untuk pengembangan dan pelatihan model machine learning. Ini menggunakan komputasi dinamis, tensor untuk representasi data, menyertakan modul autograd untuk perhitungan gradien otomatis, dan menyediakan library untuk membangun dan melatih model neural network. PyTorch memiliki fokus kuat dalam penelitian dan komunitas yang besar. Dengan fitur-fitur seperti TorchScript dan TorchServe, PyTorch juga mendukung deployment model di lingkungan produksi.

Modul ini akan membahas berbagai aspek penting dalam PyTorch, yang dibagi menjadi beberapa bagian atau notebook dengan nomor yang berurutan (misalnya, 00, 01, 02). Setiap notebook secara progresif membangun pengetahuan dari notebook sebelumnya.

Fokus dari notebook ini adalah tensor, komponen dasar dalam machine learning dan deep learning. Topik utama yang akan dibahas meliputi:

1. **Pengenalan terhadap Tensors:**
   - Tensors berperan sebagai blok dasar dalam machine learning dan deep learning.

2. **Membuat Tensors:**
   - Tensors dapat merepresentasikan berbagai jenis data, mulai dari gambar dan kata-kata hingga tabel angka.

3. **Mendapatkan Informasi dari Tensors:**
   - Selain memasukkan informasi ke dalam tensors, penting juga untuk memahami cara mengekstrak data berharga dari mereka.

4. **Manipulasi Tensors:**
   - Algoritma machine learning, khususnya jaringan saraf, melibatkan manipulasi tensors melalui operasi seperti penambahan, perkalian, dan penggabungan.

5. **Penanganan Bentuk Tensors:**
   - Menangani bentuk tensor merupakan tantangan umum dalam machine learning, melibatkan penyelesaian masalah terkait dengan ketidakcocokan bentuk tensor selama operasi.

6. **Indexing pada Tensors:**
   - Mirip dengan pengindeksan pada daftar Python atau array NumPy, tensors mendukung pengindeksan, tetapi dengan kompleksitas tambahan yang mungkin memiliki lebih banyak dimensi.

7. **Mencampur Tensors PyTorch dan NumPy:**
   - PyTorch menggunakan tensors (`torch.Tensor`), sementara NumPy lebih suka array (`np.ndarray`). Bagian ini mengeksplorasi integrasi dan pertukaran yang lancar antara keduanya.

8. **Reproducibility:**
   - Mengingat sifat eksperimental machine learning, mengelola keacakan penting untuk reproduktibilitas. Teknik untuk mengontrol keacakan di PyTorch akan dibahas.

9. **Menjalankan Tensors di GPU:**
   - Unit Pemrosesan Grafis (GPU) dapat signifikan meningkatkan eksekusi kode. PyTorch mempermudah proses menjalankan kode di GPU, meningkatkan efisiensi komputasi.

Dengan mengeksplorasi topik-topik ini, modul ini bertujuan memberikan pemahaman menyeluruh tentang konsep dasar dan teknik praktis dalam PyTorch, yang sangat penting untuk implementasi machine learning dan deep learning yang efektif.

**Importing Pytorch**

In [1]:
import torch
torch.__version__

'2.1.0+cu121'

 kode ini digunakan untuk mendapatkan informasi tentang versi PyTorch yang tengah digunakan dalam lingkungan Python yang sedang berjalan.

**Introduction to tensor**

 Tensors berfungsi untuk merepresentasikan data secara numerik. Sebagai contoh, gambar dapat diwakili sebagai tensor dengan bentuk [3, 224, 224], yang menyatakan [saluran_warna, tinggi, lebar], dengan 3 saluran warna (merah, hijau, biru), tinggi 224 piksel, dan lebar 224 piksel. Dengan menggunakan tensors, kita dapat efisien memanipulasi dan menganalisis data gambar dalam PyTorch.

In [2]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

1. **Scalar:**
   - `scalar = torch.tensor(7)`: Baris ini membuat sebuah tensor skalar dengan nilai 7 menggunakan fungsi `torch.tensor()`. Sebuah tensor skalar hanya memiliki satu nilai (tidak ada dimensi tambahan).
  
2. **Display Scalar:**
   - `scalar`: Baris ini menampilkan nilai dari tensor skalar yang telah dibuat. Hasilnya akan menunjukkan nilai 7.

Jadi, keseluruhan kode ini digunakan untuk membuat dan menampilkan sebuah tensor skalar dengan nilai 7 menggunakan PyTorch.

In [3]:
scalar.ndim

0

roperti ndim digunakan untuk mendapatkan jumlah dimensi dari sebuah tensor.Pada PyTorch, saat Anda mengecek atribut ndim pada sebuah tensor skalar, hasilnya adalah 0. Ini menunjukkan bahwa tensor skalar tidak memiliki dimensi (dimensi 0). Jadi, pada kasus ini, scalar.ndim menghasilkan nilai 0, menandakan bahwa tensor skalar tidak memiliki dimensi tambahan selain nilai tunggal yang dimilikinya.

In [4]:
# Get the Python number within a tensor (only works with one-element tensors)
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
# Check the number of dimensions of vector
vector.ndim

1

Vektor yang dibuat dengan PyTorch memiliki dua angka, namun hanya memiliki satu dimensi. Jumlah dimensi suatu tensor dalam PyTorch dapat ditentukan dari jumlah tanda kurung siku luar ([) dan Anda hanya perlu menghitung satu sisi. Pada vektor ini, terdapat satu tanda kurung siku luar, sehingga vektornya memiliki satu dimensi.

Selain itu, konsep penting lainnya untuk tensor adalah atribut bentuk (`shape`). Bentuk memberi tahu Anda bagaimana elemen-elemen di dalamnya diatur.

In [7]:
# Check shape of vector
vector.shape

torch.Size([2])

Baris kode tersebut digunakan untuk memeriksa bentuk (shape) dari vektor yang telah dibuat sebelumnya. Berikut adalah penjelasan singkat:

1. **Check Shape of Vector:**
   - `vector.shape`: Baris ini mengembalikan atribut bentuk dari vektor. Hasilnya menunjukkan bahwa bentuk vektor adalah `torch.Size([2])`.
   - `[2]` mengindikasikan bahwa vektor memiliki 2 elemen, sesuai dengan jumlah angka yang terdapat dalam vektor tersebut.

Jadi, vektor ini memiliki bentuk (shape) `[2]`, menunjukkan bahwa vektor tersebut merupakan tensor satu dimensi dengan dua elemen.

In [8]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
# Check number of dimensions
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [12]:
# Check number of dimensions for TENSOR
TENSOR.ndim

3

In [13]:
# Check shape of TENSOR
TENSOR.shape

torch.Size([1, 3, 3])

Kode tersebut membuat, menampilkan, dan memeriksa atribut dimensi (number of dimensions) serta bentuk (shape) dari sebuah tensor tiga dimensi menggunakan PyTorch. Berikut adalah penjelasan singkat:

1. **Tensor Creation:**
   - `TENSOR = torch.tensor([[[1, 2, 3], [3, 6, 9], [2, 4, 5]]])`: Baris ini membuat sebuah tensor tiga dimensi dengan nilai-nilai yang disediakan.

2. **Display Tensor:**
   - `TENSOR`: Baris ini menampilkan nilai dari tensor tiga dimensi yang telah dibuat.

3. **Check Number of Dimensions for Tensor:**
   - `TENSOR.ndim`: Baris ini mengembalikan jumlah dimensi dari tensor. Dalam kasus ini, tensor memiliki tiga dimensi, sesuai dengan tiga tingkat tanda kurung siku dalam pembuatannya.

4. **Check Shape of Tensor:**
   - `TENSOR.shape`: Baris ini mengembalikan atribut bentuk dari tensor. Hasilnya menunjukkan bahwa bentuk tensor adalah `torch.Size([1, 3, 3])`.
   - `[1, 3, 3]` mengindikasikan bahwa tensor ini memiliki dimensi pertama sejumlah 1, dimensi kedua sejumlah 3, dan dimensi ketiga sejumlah 3.

Jadi, secara keseluruhan, kode ini menciptakan, menampilkan, dan memeriksa informasi dimensi dan bentuk dari sebuah tensor tiga dimensi.

**Random Tensor**

Random tensor adalah tensor yang diisi dengan nilai-nilai acak. Dalam PyTorch, Anda dapat membuat random tensor menggunakan fungsi-fungsi tertentu dari modul `torch` atau `torch.rand`, `torch.randn`, dan lainnya. Berikut adalah penjelasan singkat tentang beberapa cara membuat random tensor:

1. **torch.rand():**
   - Menghasilkan random tensor dengan nilai-nilai acak yang berada di antara 0 dan 1, dengan distribusi seragam (uniform distribution).
   - Contoh: `torch.rand(3, 4)` akan menghasilkan tensor 3x4 dengan nilai acak antara 0 dan 1.

2. **torch.randn():**
   - Menghasilkan random tensor dengan nilai-nilai acak yang diambil dari distribusi normal dengan mean 0 dan variansi 1 (distribusi normal standar).
   - Contoh: `torch.randn(2, 2)` akan menghasilkan tensor 2x2 dengan nilai acak dari distribusi normal standar.

3. **torch.randint():**
   - Menghasilkan random tensor dengan nilai-nilai integer acak dalam suatu range tertentu.
   - Contoh: `torch.randint(low=1, high=10, size=(3, 3))` akan menghasilkan tensor 3x3 dengan nilai integer acak antara 1 dan 10.

4. **torch.randperm():**
   - Menghasilkan random tensor yang berisi permutasi acak dari nilai-nilai integer dari 0 hingga n-1.
   - Contoh: `torch.randperm(5)` akan menghasilkan tensor yang mungkin mirip dengan `[2, 4, 1, 0, 3]`.

Random tensor sering digunakan dalam inisialisasi parameter model, augmentasi data, atau dalam situasi-situasi lain di mana keberagaman nilai-nilai acak diperlukan.

In [14]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.7735, 0.6364, 0.3489, 0.3930],
         [0.4112, 0.5830, 0.4076, 0.1192],
         [0.3758, 0.6786, 0.7624, 0.4031]]),
 torch.float32)

Fungsi `torch.rand()` memberikan fleksibilitas untuk menyesuaikan ukuran (size) tensor sesuai kebutuhan. Dalam contoh yang diberikan, kita ingin membuat random tensor dengan bentuk yang umum digunakan dalam representasi gambar, yaitu [224, 224, 3], yang menyatakan [tinggi, lebar, saluran warna].



In [15]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

Dalam beberapa situasi, Anda mungkin ingin mengisi tensor dengan nilai nol atau satu. Hal ini umumnya digunakan dalam konteks penggunaan mask (penyaringan), seperti saat memasukkan nilai-nilai nol ke dalam suatu tensor untuk memberi tahu model agar tidak mempelajarinya.

Untuk membuat tensor yang diisi dengan nilai nol, kita dapat menggunakan fungsi `torch.zeros()`. Fungsi ini membutuhkan parameter `size` untuk menentukan ukuran (shape) dari tensor yang akan dibuat.



In [16]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [17]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

erkadang Anda mungkin menginginkan rentang angka, seperti 1 hingga 10 atau 0 hingga 100.

Anda dapat menggunakan torch.arange(start, end, step) untuk melakukannya.


In [18]:
# Use torch.arange(), torch.range() is deprecated
zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future

# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

<ipython-input-18-a09072c806d9>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Seringkali, Anda mungkin ingin membuat tensor lain dengan jenis tertentu dan bentuk yang sama dengan tensor lainnya. Misalnya, membuat tensor berisi nilai-nol dengan bentuk yang sama seperti tensor sebelumnya.

Dalam PyTorch, Anda dapat menggunakan `torch.zeros_like(input)` atau `torch.ones_like(input)` untuk mencapai ini. Kedua fungsi ini menghasilkan tensor yang diisi dengan nilai-nol atau satu, sesuai dengan bentuk (shape) tensor input yang diberikan.


In [19]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

**Tensor Datatypes**

Data type (tipe data) dalam PyTorch mengacu pada jenis nilai atau format representasi numerik yang dapat disimpan dalam tensor. PyTorch mendukung berbagai tipe data, dan pemilihan tipe data dapat mempengaruhi ukuran memori yang diperlukan dan rentang nilai yang dapat diwakili oleh tensor. Berikut beberapa tipe data umum dalam PyTorch:

1. **torch.float32 (float):**
   - Tipe data default untuk bilangan real (float) dalam PyTorch.
   - Mewakili bilangan real dengan presisi 32-bit (single precision).

2. **torch.float64 (double):**
   - Tipe data untuk bilangan real dengan presisi 64-bit (double precision).
   - Memberikan presisi yang lebih tinggi dibandingkan dengan float32, namun membutuhkan lebih banyak ruang memori.

3. **torch.float16 (half):**
   - Tipe data floating-point dengan presisi setengah (half precision).
   - Umumnya digunakan untuk mempercepat operasi pada perangkat keras tertentu seperti GPU.

4. **torch.int8, torch.int16, torch.int32, torch.int64:**
   - Tipe data untuk bilangan bulat dengan berbagai panjang bit (8-bit, 16-bit, 32-bit, dan 64-bit).
   - Panjang bit mempengaruhi rentang nilai yang dapat diwakili dan penggunaan memori.

5. **torch.uint8:**
   - Tipe data untuk bilangan bulat tanpa tanda (unsigned integer) dengan panjang bit 8-bit.
   - Digunakan untuk representasi nilai non-negatif.

6. **torch.bool:**
   - Tipe data boolean, dapat bernilai `True` atau `False`.
   - Digunakan untuk operasi logika dan indeksasi boolean pada tensor.

Pemilihan tipe data yang sesuai penting dalam pengembangan model machine learning karena dapat mempengaruhi kinerja dan penggunaan memori. Pada umumnya, penggunaan float32 adalah standar default, tetapi dalam beberapa kasus, penggunaan tipe data lainnya seperti float16 atau int8 dapat bermanfaat untuk mengoptimalkan performa dan penggunaan memori.

In [20]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [21]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

**Getting Information From Tensors**

In [22]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.3043, 0.3190, 0.5498, 0.4550],
        [0.8087, 0.2128, 0.1406, 0.8739],
        [0.6782, 0.4125, 0.5859, 0.7200]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


***Manipulating Tensors (tensors operation) ***

Pada dasarnya, dalam deep learning, data diwakili sebagai tensor, dan model belajar dengan menyelidiki tensor tersebut melalui serangkaian operasi, yang sering kali melibatkan operasi matematika dasar. Berikut adalah beberapa operasi matematika yang umum digunakan dalam deep learning:

1. **Addition (Penambahan):**
   - Menggabungkan nilai-nilai dua tensor pada posisi yang sesuai, elemen demi elemen.
   - Contoh: `C = A + B` akan menghasilkan tensor `C` di mana setiap elemen `C[i, j] = A[i, j] + B[i, j]`.

2. **Subtraction (Pengurangan):**
   - Mengurangkan nilai-nilai satu tensor dari tensor lain pada posisi yang sesuai, elemen demi elemen.
   - Contoh: `C = A - B` menghasilkan tensor `C` dengan setiap elemen `C[i, j] = A[i, j] - B[i, j]`.

3. **Multiplication (Element-wise) (Perkalian Elemen):**
   - Mengalikan nilai-nilai dua tensor pada posisi yang sesuai, elemen demi elemen.
   - Contoh: `C = A * B` menghasilkan tensor `C` dengan setiap elemen `C[i, j] = A[i, j] * B[i, j]`.

4. **Division (Pembagian):**
   - Membagi nilai-nilai satu tensor dengan tensor lain pada posisi yang sesuai, elemen demi elemen.
   - Contoh: `C = A / B` menghasilkan tensor `C` dengan setiap elemen `C[i, j] = A[i, j] / B[i, j]`.

5. **Matrix Multiplication (Perkalian Matriks):**
   - Mengalikan dua matriks untuk menghasilkan matriks baru.
   - Contoh: `C = A @ B` atau `C = torch.matmul(A, B)` menghasilkan hasil perkalian matriks `C` dari matriks `A` dan `B`.

Operasi-operasi ini membentuk dasar untuk transformasi dan representasi data dalam model deep learning. Matriks multiplication, khususnya, memiliki peran penting dalam menghubungkan layer-layer dalam jaringan saraf dan mengekstraksi fitur yang kompleks dari data.


**Basic Operation**

In [23]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [24]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])

In [25]:
#Notice how the tensor values above didn't end up being tensor([110, 120, 130]), this is because the values inside the tensor don't change unless they're reassigned.
# Tensors don't change unless reassigned
tensor

tensor([1, 2, 3])

In [26]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [27]:
# Add and reassign
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [28]:
#PyTorch also has a bunch of built-in functions like torch.mul() (short for multiplication) and torch.add() to perform basic operations.
# Can also use torch functions
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [29]:
# Original tensor is still unchanged
tensor

tensor([1, 2, 3])

In [30]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


**Matrix Multiplication**

In [31]:
import torch
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

In [32]:
# Element-wise matrix multiplication
tensor * tensor

tensor([1, 4, 9])

In [33]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [34]:
# Can also use the "@" symbol for matrix multiplication, though not recommended
tensor @ tensor

tensor(14)

In [35]:
%%time
# Matrix multiplication by hand
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 588 µs, sys: 0 ns, total: 588 µs
Wall time: 5.59 ms


tensor(14)

In [36]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 87 µs, sys: 0 ns, total: 87 µs
Wall time: 91.1 µs


tensor(14)

**One of the most common errors in deep learning (shape errors)**

In [38]:
#Because much of deep learning is multiplying and performing operations on matrices and matrices have a strict rule about what shapes and sizes can be combined, one of the most common errors you'll run into in deep learning is shape mismatches.
# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: ignored

 Untuk membuat perkalian matriks berhasil antara tensor_A dan tensor_B, dimensi dalam tensor tersebut harus sesuai (inner dimensions harus sama). Salah satu cara untuk mencapai hal ini adalah dengan melakukan operasi transpose, yang mengubah dimensi-dimensi tensor.

Dalam PyTorch, Anda dapat melakukan transpose menggunakan salah satu dari dua metode:

1. **torch.transpose(input, dim0, dim1):**
   - Fungsi ini mentranspose tensor `input` dengan menukar dimensi `dim0` dan `dim1`.
   - Contoh: `C = torch.transpose(A, 0, 1)` akan mentranspose tensor `A`, menukar dimensi pertama dan kedua.

2. **tensor.T:**
   - Menghasilkan transpose dari tensor `tensor`.
   - Contoh: `C = A.T` akan menghasilkan transpose dari tensor `A`.



In [39]:
# View tensor_A and tensor_B
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [40]:
# View tensor_A and tensor_B.T
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [41]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


In [42]:
#You can also use torch.mm() which is a short for torch.matmul().
# torch.mm is a shortcut for matmul
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [43]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input
                         out_features=6) # out_features = describes outer value
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


**Finding the min, max, mean, sum, etc (aggregation)**

In [44]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [45]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [46]:
#You can also do the same as above with torch methods.
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

**Positional min/max**

In [47]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


**Change tensor datatype**

In [48]:
# Create a tensor and check its datatype
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [49]:
# Now we'll create another tensor the same as before but change its datatype to torch.float16.
# Create a float16 tensor
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [50]:
# And we can do something similar to make a torch.int8 tensor.
# Create a int8 tensor
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

**Reshaping, stacking, squeezing and unsqueezing**

1. **`torch.reshape(input, shape)` atau `torch.Tensor.reshape(shape)`:**
   - Mengubah bentuk tensor `input` menjadi bentuk yang ditentukan oleh parameter `shape`.
   - Contoh: `B = torch.reshape(A, (3, 4))` mengubah bentuk tensor `A` menjadi matriks 3x4.

2. **`Tensor.view(shape)`:**
   - Mengembalikan pandangan (view) dari tensor asli dengan bentuk yang berbeda, tetapi berbagi data yang sama dengan tensor asli.
   - Contoh: `B = A.view(3, 4)` menghasilkan view dari tensor `A` dengan bentuk matriks 3x4.

3. **`torch.stack(tensors, dim=0)`:**
   - Menggabungkan sekuens tensor sepanjang dimensi baru (dim), dengan syarat semua tensor harus memiliki ukuran yang sama.
   - Contoh: `C = torch.stack([A, B])` menggabungkan tensor A dan B sepanjang dimensi baru (stack).

4. **`torch.squeeze(input)`:**
   - Menghapus dimensi yang memiliki nilai 1 dari tensor input.
   - Contoh: `B = torch.squeeze(A)` menghilangkan dimensi yang memiliki panjang 1 dari tensor A.

5. **`torch.unsqueeze(input, dim)`:**
   - Menambah dimensi dengan nilai 1 pada posisi yang ditentukan oleh parameter `dim`.
   - Contoh: `B = torch.unsqueeze(A, 1)` menambah dimensi dengan nilai 1 pada posisi kedua pada tensor A.

6. **`torch.permute(input, dims)`:**
   - Menghasilkan pandangan dari input dengan dimensinya yang diurutkan (rearranged) sesuai dengan urutan yang ditentukan oleh `dims`.
   - Contoh: `B = torch.permute(A, (1, 0))` menukar dimensi pertama dan kedua pada tensor A.

Mengapa kita membutuhkan metode-metode ini? Karena dalam model deep learning (neural networks), manipulasi tensor adalah kunci, dan aturan perkalian matriks memerlukan kesesuaian bentuk tensor. Jika terdapat ketidakcocokan bentuk, kita dapat mengalami kesalahan. Metode-metode ini membantu memastikan bahwa elemen-elemen yang benar dari tensor kita bersatu dengan elemen-elemen yang benar dari tensor lainnya. Dengan kata lain, metode-metode ini membantu menjaga konsistensi bentuk tensor, memungkinkan operasi matematis dan perkalian matriks berjalan dengan benar dalam model deep learning.


In [51]:
# Create a tensor
import torch
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [52]:
# Now let's add an extra dimension with torch.reshape().
# Add an extra dimension
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [54]:
#  We can also change the view with torch.view().
# Change view (keeps same data as original but changes view)
# See more: https://stackoverflow.com/a/54507446/7900723
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [55]:
# Changing z changes x
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [56]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [57]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


Kode ini mencakup operasi pada tensor PyTorch untuk mengubah bentuk dan menghilangkan dimensi yang tidak diperlukan. Mari kita jelaskan langkah-langkahnya:

```python
# Menampilkan tensor sebelum perubahan bentuk
print(f"Previous tensor: {x_reshaped}")
# Menampilkan bentuk (shape) tensor sebelum perubahan bentuk
print(f"Previous shape: {x_reshaped.shape}")

# Menghilangkan dimensi tambahan dari x_reshaped
x_squeezed = x_reshaped.squeeze()

# Menampilkan tensor setelah dimensi dihilangkan
print(f"\nNew tensor: {x_squeezed}")
# Menampilkan bentuk (shape) tensor setelah dimensi dihilangkan
print(f"New shape: {x_squeezed.shape}")
```

Penjelasan singkat:
1. `print(f"Previous tensor: {x_reshaped}")`: Menampilkan nilai dari tensor sebelum perubahan bentuk.
2. `print(f"Previous shape: {x_reshaped.shape}")`: Menampilkan bentuk (shape) tensor sebelum perubahan bentuk.
3. `x_squeezed = x_reshaped.squeeze()`: Menghilangkan dimensi tambahan dari tensor `x_reshaped`. Jika ada dimensi yang memiliki panjang 1, dimensi tersebut akan dihapus.
4. `print(f"\nNew tensor: {x_squeezed}")`: Menampilkan nilai tensor setelah dimensi dihilangkan.
5. `print(f"New shape: {x_squeezed.shape}")`: Menampilkan bentuk (shape) tensor setelah dimensi dihilangkan.

Operasi `squeeze()` berguna ketika Anda ingin menghilangkan dimensi yang tidak perlu dan membuat tensor menjadi lebih "rata". Ini sering digunakan untuk mempersiapkan data sebelum dimasukkan ke dalam model deep learning atau dalam situasi di mana dimensi yang tidak diinginkan muncul selama manipulasi data.

In [ ]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Kode ini mencakup operasi untuk menambahkan dimensi tambahan ke dalam tensor menggunakan metode `unsqueeze`. Berikut adalah penjelasan langkah-langkahnya:

```python
# Menampilkan tensor sebelum dimensi ditambahkan
print(f"Previous tensor: {x_squeezed}")
# Menampilkan bentuk (shape) tensor sebelum dimensi ditambahkan
print(f"Previous shape: {x_squeezed.shape}")

# Menambahkan dimensi tambahan ke x_squeezed
x_unsqueezed = x_squeezed.unsqueeze(dim=0)

# Menampilkan tensor setelah dimensi ditambahkan
print(f"\nNew tensor: {x_unsqueezed}")
# Menampilkan bentuk (shape) tensor setelah dimensi ditambahkan
print(f"New shape: {x_unsqueezed.shape}")
```

Penjelasan singkat:
1. `print(f"Previous tensor: {x_squeezed}")`: Menampilkan nilai dari tensor sebelum dimensi ditambahkan.
2. `print(f"Previous shape: {x_squeezed.shape}")`: Menampilkan bentuk (shape) tensor sebelum dimensi ditambahkan.
3. `x_unsqueezed = x_squeezed.unsqueeze(dim=0)`: Menambahkan dimensi tambahan ke tensor `x_squeezed` pada posisi 0 (dimensi pertama).
4. `print(f"\nNew tensor: {x_unsqueezed}")`: Menampilkan nilai tensor setelah dimensi ditambahkan.
5. `print(f"New shape: {x_unsqueezed.shape}")`: Menampilkan bentuk (shape) tensor setelah dimensi ditambahkan.

Operasi `unsqueeze` berguna ketika Anda ingin menambahkan dimensi tambahan ke dalam tensor, misalnya, untuk menyesuaikan dengan kebutuhan model atau operasi tertentu dalam deep learning.

In [58]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


Kode ini menciptakan tensor dengan bentuk (shape) awal tertentu menggunakan `torch.rand` dan kemudian merubah urutan sumbu (axis) tensor tersebut menggunakan metode `permute`. Berikut adalah penjelasan singkatnya:

```python
# Membuat tensor dengan bentuk (shape) tertentu
x_original = torch.rand(size=(224, 224, 3))

# Mengubah urutan sumbu tensor dengan metode permute
x_permuted = x_original.permute(2, 0, 1)  # menggeser sumbu 0->1, 1->2, 2->0

# Menampilkan bentuk (shape) sebelum dan setelah permutasi
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")
```

Penjelasan singkat:
1. `x_original = torch.rand(size=(224, 224, 3))`: Membuat tensor dengan bentuk (shape) 224x224x3, yang mewakili gambar dengan dimensi tinggi, lebar, dan saluran warna RGB.
2. `x_permuted = x_original.permute(2, 0, 1)`: Menggunakan metode `permute` untuk mengubah urutan sumbu tensor. Dalam hal ini, sumbu ke-0 menjadi sumbu ke-1, sumbu ke-1 menjadi sumbu ke-2, dan sumbu ke-2 menjadi sumbu ke-0.
3. `print(f"Previous shape: {x_original.shape}")`: Menampilkan bentuk (shape) tensor sebelum permutasi.
4. `print(f"New shape: {x_permuted.shape}")`: Menampilkan bentuk (shape) tensor setelah permutasi.

Operasi `permute` seringkali berguna dalam pengolahan citra dan penggunaan model deep learning di mana struktur sumbu tensor harus diubah untuk memenuhi kebutuhan tertentu. Dalam kasus ini, permutasi digunakan untuk mengganti urutan sumbu sehingga tensor lebih sesuai dengan format yang umum digunakan dalam jaringan saraf konvolusional (CNN).

**Indexing Selecting Data From Tensor**

In [59]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [60]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}")
print(f"Second square bracket: {x[0][0]}")
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [61]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

In [62]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [63]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [64]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])

**Pytorch tensors & NumPy**

In [65]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [66]:
# Change the array, keep the tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [67]:
# And if you want to go from PyTorch tensor to NumPy array, you can call tensor.numpy().
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [68]:
# And the same rule applies as above, if you change the original tensor, the new numpy_tensor stays the same.
# Change the tensor, keep the array the same
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

**Reproducibility (trying to take the random out of random)**

1. **Pseudorandomness:** Randomness di komputer sebenarnya bersifat pseudorandom karena komputer pada dasarnya bersifat deterministik.
2. **Peran Ketidakpastian dalam Neural Networks:** Neural networks memulai dengan angka-angka acak untuk menggambarkan pola dalam data dan berusaha meningkatkannya melalui operasi tensor.
3. **Proses Iteratif Deep Learning:** Deep learning melibatkan iterasi berulang yang dimulai dengan angka-angka acak dan berlanjut dengan operasi tensor untuk meningkatkan representasi data.
4. **Reproducibility dan Konsistensi:** Reproducibility penting agar eksperimen dapat diulang, dan hasil yang sama atau mirip dapat dicapai pada komputer yang berbeda dengan menjalankan kode yang sama.
5. **Contoh Reproducibility dalam PyTorch:** Membuat dua tensor acak untuk menunjukkan keinginan mendapatkan hasil yang konsisten saat menjalankan kode yang sama.

Pentingnya reproducibility adalah untuk memastikan konsistensi hasil dan memungkinkan verifikasi eksperimen oleh orang lain.

In [69]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.8016, 0.3649, 0.6286, 0.9663],
        [0.7687, 0.4566, 0.5745, 0.9200],
        [0.3230, 0.8613, 0.0919, 0.3102]])

Tensor B:
tensor([[0.9536, 0.6002, 0.0351, 0.6826],
        [0.3743, 0.5220, 0.1336, 0.9666],
        [0.9754, 0.8474, 0.8988, 0.1105]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

**Running tensors on GPUs (and making faster computations)**

In [70]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


Kode tersebut berguna untuk memeriksa apakah kita memiliki akses terhadap GPU Nvidia

In [71]:
# Check for GPU
import torch
torch.cuda.is_available()

False

Kode tersebut berguna untuk memriksa apakah pytorch memiliki akses kepada GPu

In [72]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

Kode tersebut menetapkan tipe perangkat yang akan digunakan (GPU atau CPU) berdasarkan ketersediaan GPU pada sistem. Berikut adalah penjelasan singkatnya:

```python
device = "cuda" if torch.cuda.is_available() else "cpu"
```

- `torch.cuda.is_available()`: Memeriksa apakah GPU (cuda) tersedia pada sistem.
- `device = "cuda" if torch.cuda.is_available() else "cpu"`: Menetapkan nilai variabel `device` ke "cuda" jika GPU tersedia, dan ke "cpu" jika tidak.
- `device`: Menampilkan tipe perangkat yang akan digunakan (cuda atau cpu).

Dengan pendekatan ini, kode dapat berjalan pada GPU jika tersedia, dan jika tidak, akan beralih ke penggunaan CPU. Hal ini berguna untuk memastikan fleksibilitas dan ketersediaan kode pada berbagai konfigurasi perangkat keras.

In [73]:
# Count number of devices
torch.cuda.device_count()

0

**Putting tensors (and models) on the GPU**

In [74]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3])

Kode ini menciptakan tensor di CPU dan kemudian memindahkannya ke GPU jika GPU tersedia. Berikut adalah penjelasan singkatnya:

```python
# Membuat tensor (default di CPU)
tensor = torch.tensor([1, 2, 3])

# Menampilkan tensor dan perangkat tempat tensor berada (CPU)
print(tensor, tensor.device)

# Memindahkan tensor ke GPU (jika tersedia)
tensor_on_gpu = tensor.to(device)
```

- `tensor = torch.tensor([1, 2, 3])`: Menciptakan tensor di CPU dengan nilai [1, 2, 3].
- `print(tensor, tensor.device)`: Menampilkan tensor dan perangkat tempat tensor berada (di CPU).
- `tensor_on_gpu = tensor.to(device)`: Memindahkan tensor ke perangkat yang telah ditentukan sebelumnya (CPU atau GPU, sesuai ketersediaan).

Dengan pendekatan ini, Anda dapat membuat tensor di CPU dan kemudian memindahkannya ke GPU jika diperlukan, memberikan fleksibilitas dalam penggunaan perangkat keras tanpa mengubah secara signifikan struktur kode.

**Moving tensors back to the CPU**

In [75]:
# If tensor is on GPU, can't transform it to NumPy (this will error)
tensor_on_gpu.numpy()

array([1, 2, 3])

Kode ini pada dasarnya harusnya error. Disini tidak erro dikarenakan google colab yang saya gunakan saat ini tidak memiliki akses kepada GPU

In [76]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [77]:
tensor_on_gpu

tensor([1, 2, 3])